config/routes.rb
Rails.application.routes.draw do


  root to: 'homes#top'
  get 'homes/about'

# 顧客用
# URL /customers/sign_in ...
devise_for :members,skip: [:passwords,], controllers: {
  registrations: "member/registrations",
  sessions: 'member/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admins, skip: [:passwords] ,controllers: {
  sessions: "admin/sessions",
  registrations: 'admin/registrations'
}

  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
  end

  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
  end

  namespace :admin do
    resources :members, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    resources :orders, only: [:index, :show, :update]
  end

  namespace :admin do
    resources :order_details, only: [:update]
  end

  namespace :public do
    resources :deliveries, only: [:index, :edit, :create, :update, :destroy]
  end

  namespace :public do
    get 'orders/confirm' => 'orders#confirm', as: 'confirm'
    get 'orders/complete' => 'orders#complete', as: 'complete'
    resources :orders, only: [:index, :new, :show, :create]
  end

  namespace :public do
    get 'search' => 'items#search'
    resources :items, only: [:index, :show]
  end

  namespace :public do
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    resources :cart_items, only: [:index, :create, :destroy, :update]
  end

  namespace :public do
    get 'members/show' => 'members#show', as: 'mypage'
    get 'members/unsubscribe' => 'members#unsubscribe', as: 'unsubscribe'
    patch 'members/withdrawal' => 'members#withdrawal', as: 'withdrawal'
    resources :members, only: [:edit, :update]
  end

  namespace :public do
    resources :genres, only: [:show]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :member
  belongs_to :item
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :member
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  has_many :cart_items, dependent: :destroy
  has_many :oder_details, dependent: :destroy
  belongs_to :genre
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def active_for_authentication?
    super && (is_deleted == false)
  end
  
  has_many :deliveries, dependent: :destroy
  has_many :oders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
end

app/models/oder.rb
class Oder < ApplicationRecord
  belongs_to :member
  has_many :oder_details, dependent: :destroy

end

app/models/oder_detail.rb
class OderDetail < ApplicationRecord
  belongs_to :oder
  belongs_to :item

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)

  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
  end

  def update
  end

  private

  def item_params
    params.require(:item).permit(:name, :body, :image, :price, :is_active, :genre_id)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    case resource
        when Admin
          admin_orders_path
        when Member
          mypage_path
    end
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/member/homes_helper.rb
module Member::HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
       <div class="container">
         <a class="navbar-brand" href="/",class: 'd-inline-block'>naganocake</a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
         </button>

         <div class="collapse navbar-collapse" id="navbarNavDropdown">

       <ul class="navbar-nav ml-auto">

        <% if member_signed_in? %>

         <li>
            <%= link_to public_mypage_path(current_member) do %>
              <i class="fas fa-home nav-link text-light"> マイページ</i>
            <% end %>
         </li>
         <li>
           <%= link_to public_items_path do %>
              <i class="fas fa-users nav-link text-light"> 商品一覧</i>
           <% end %>
         </li>
         <li>
           <%= link_to public_cart_items_path do %>
              <i class="fas fa-book-open nav-link text-light"> カート</i>
           <% end %>
         </li>
         <li>
           <%= link_to destroy_member_session_path, method: :delete do %>
              <i class="fas fa-sign-out-alt nav-link text-light"> ログアウト</i>
           <% end %>
         </li>

         <% elsif admin_signed_in? %>

         <li>
            <%= link_to admin_items_path do %>
              <i class="fas fa-home nav-link text-light"> 商品一覧</i>
            <% end %>
         </li>
         <li>
           <%= link_to admin_members_path do %>
              <i class="fas fa-users nav-link text-light"> 会員一覧</i>
           <% end %>
         </li>
         <li>
           <%= link_to admin_orders_path do %>
              <i class="fas fa-book-open nav-link text-light"> 注文履歴一覧</i>
           <% end %>
         </li>
         <li>
           <%= link_to admin_genres_path do %>
              <i class="fas fa-book-open nav-link text-light"> ジャンル一覧</i>
           <% end %>
         </li>
         <li>
           <%= link_to destroy_admin_session_path, method: :delete do %>
              <i class="fas fa-sign-out-alt nav-link text-light"> ログアウト</i>
           <% end %>
         </li>

        <% else %>

         <li>
           <%= link_to root_path do %>
              <i class="fas fa-home nav-link text-light"> Home</i>
           <% end %>
         </li>
         <li>
           <%= link_to homes_about_path do %>
              <i class="fas fa-link nav-link text-light"> About</i>
           <% end %>
         </li>
         <li>
           <%= link_to public_items_path do %>
              <i class="fas fa-user-plus nav-link text-light"> 商品一覧</i>
           <% end %>
         </li>
         <li>
           <%= link_to new_member_session_path do %>
              <i class="fas fa-sign-in-alt nav-link text-light"> ログイン</i>
           <% end %>
         </li>

        </ul>
        <% end %>

       </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>